vim.keymap.set('n', '<leader>dl', function()
  require('dap').step_into()
end, { desc = '[D]ebug step into [l]' })
vim.keymap.set('n', '<leader>dj', function()
  require('dap').step_over()
end, { desc = '[D]ebug step over [j]' })
vim.keymap.set('n', '<leader>dk', function()
  require('dap').step_out()
end, { desc = '[D]ebug step out [k]' })
vim.keymap.set('n', '<leader>dg', function()
  require('dap').continue()
end, { desc = '[D]ebug continue. [g]o' })
vim.keymap.set('n', '<leader>db', function()
  require('dap').toggle_breakpoint()
end, { desc = '[D]ebug toggle [b]reakpoint' })
vim.keymap.set('n', '<leader>dt', function()
  require('dapui').toggle()
end, { desc = '[D]ebug [t]oggle dapui' })
